### ISSUE TITLE
Can't start app

### ISSUE THREAD

**Issue by jinlan** [Mehni/ModSorter#1]
An error thrown right after I try to start app.
My OS: win7
Then I tried to put it RW root folder, RW mod folder, not working.

**Comment by KongMD-Steam** [comment]
Temporary fix: Comment out lines 21 through 25 in MainWindow.xaml and recompile. An image file is missing, so the app won't start.

**Comment by Mehni** [comment]
Fixed. Redownload from releases. Thanks @KongMD-Steam for the pointer.
